{
 "title": "Pi-hole",
 "description": "This is a PI-hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "tags": [
  "pi-hole",
  "network",
  "dns"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pihole", "label": "Pi-hole", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Pi-hole",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_status{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_unique_domains{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_top_queries{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_reply{instance=\"$pihole\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_top_ads{instance=\"$pihole\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_dns_queries_all_types{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_queries_cached{instance=\"$pihole\"}",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "pihole_queries_forwarded{instance=\"$pihole\"}",
     "legendFormat": "Queries forwarded"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pihole_querytypes{instance=\"$pihole\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{instance=\"$pihole\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "pihole_top_queries{instance=\"$pihole\"}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "pihole_top_ads{instance=\"$pihole\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pihole_forward_destinations{instance=\"$pihole\"}",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_unique_clients{instance=\"$pihole\"}"
    }
   ]
  }
 ]
}